<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="L-CDZ6152" ignored="0" name="Backend Services" tests="15" failures="1" timestamp="18 Jul 2019 09:16:47 GMT" time="0.101" errors="0">
  <testcase name="test1" time="0.01" classname="grouping.TestNGGroupDemo"/>
  <testcase name="test2" time="0.002" classname="grouping.TestNGGroupDemo"/>
  <testcase name="test3" time="0.002" classname="grouping.TestNGGroupDemo"/>
  <testcase name="test4" time="0.002" classname="grouping.TestNGGroupDemo"/>
  <testcase name="test5" time="0.001" classname="grouping.TestNGGroupDemo"/>
  <testcase name="test1" time="0.001" classname="listeners.TestNGListenerDemo"/>
  <testcase name="test2" time="0.004" classname="listeners.TestNGListenerDemo"/>
  <testcase name="test3" time="0.002" classname="listeners.TestNGListenerDemo"/>
  <testcase name="test4" time="0.001" classname="listeners.TestNGListenerDemo2"/>
  <testcase name="test5" time="0.001" classname="listeners.TestNGListenerDemo2"/>
  <testcase name="test6" time="0.001" classname="listeners.TestNGListenerDemo2"/>
  <testcase name="test1" time="0.002" classname="retry_fail_cases.TestNGRetryFailDemo"/>
  <testcase name="test2" time="0.001" classname="retry_fail_cases.TestNGRetryFailDemo"/>
  <testcase name="test3" time="0.008" classname="retry_fail_cases.TestNGRetryFailDemo">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="retry_fail_cases.TestNGRetryFailDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retry_fail_cases.TestNGRetryFailDemo.test3(TestNGRetryFailDemo.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Backend Services -->
